### PR TITLE
a few speed-ups to k2mosaic

### PR DESCRIPTION
**Pull request by mirca**
@gully and @mirca have been working on boosting ``k2mosaic`` by using the ``fitsio`` library instead of ``astropy.io.fits``.

### CODE REVIEW

**Comment by barentsen** [comment]
Can you add `fitsio` as a dependency in `setup.py`?  The tests are failing because of this.

**Comment by barentsen** [comment]
Looks good! :strawberry: :strawberry: :cake:

**Comment by mirca** [comment]
Three different authors in a single (< 50 lines) PR... Folks, we are breaking records xD

**Comment by barentsen** [comment]
It's interesting that the tests take >20 mins to run, considering the unit tests cover almost nothing.

**Comment by barentsen** [comment]
Oh wow the unit tests are compiling the entire universe.

**Pull request merged**
