### PR TITLE
Corrects broken version of k2mosaic

### PR DESCRIPTION
**Pull request by amcody**
Writes in the proper image header and also corrects problem with writing all data to the lower left corner and populating the rest of the image with nans.

### CODE REVIEW

**Comment by amcody** [comment]
@barentsen this PR is ready for review!

**Comment by barentsen** [comment]
Thanks @amcody!  These fixes make a lot of sense to me.

I will be merging this as soon as Travis passes!

**Comment by barentsen** [comment]
Travis passes!  Merging in 3 ... 2 ...

**Comment by barentsen** [comment]
I have released K2mosaic v3.0.1 via pypi to incorporate this critical bugfix!

**Pull request merged**
