### PR TITLE
use astropy.download_file whenever the filename is url

### LINKED ISSUE #15: URL Scraping Doesn't Work
In the previous version of k2 mosaic you could pass URLs. These would be downloaded and then the mosaic would automatically know where they are. Now k2mosaic breaks as it's looking for a local file.

The list of URLs is generated with the command tpflist. Example:

`$ k2mosaic tpflist 7 65 > list-of-target-pixel-files.txt`

It would be really great to have this feature back.

### PR DESCRIPTION
**Pull request by mirca**
this should be enough to fix #15 

cc @barentsen @christinahedges

### CODE REVIEW

**Comment by mirca** [comment]
@barentsen should we warn users about files being downloaded to .astropy/cache?

**Comment by mirca** [comment]
On a second thought, I would prefer not to print anything, but rather update the docs. What do you think, @barentsen?

**Comment by barentsen** [comment]
Maybe there should be a `--cache` flag which is disabled by default?

It's pretty annoying to have a tool use a large quantity of disk space in some obscure .cache directory without warning the user.

**Comment by barentsen** [comment]
I'm going to merge this because the master is broken otherwise.

I'll open a new issue to continue discussing if we want to warn the user about the cache.

**Comment by mirca** [comment]
Cool!

**Pull request merged**
